# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  # config.ssh.username = 'root'
  # config.ssh.password = 'vagrant'
  # config.ssh.insert_key = 'true'
  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
  vb.memory = 2048
  vb.cpus = 1
  end

  # Network settings
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct:"true"
  config.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct:"true"
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", ip:"148.204.64.166"

 # Provision Settings
  config.vm.provision "shell", path: "bootstrap.sh"
  # Folder Settings
  config.vm.synced_folder "./News", "/var/www/html/News", id:"website"
  config.vm.synced_folder "sqlprueba", "/prueba", id: "mysql"
  config.vm.synced_folder "Scripts", "/scripts", id: "scripts"

end

# mysql -u root -proot document_analyzer < synonym.sql